services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: lbbs
      MYSQL_USER: lbbs
      MYSQL_PASSWORD: YjM2ZmRmODNmYmE
    networks:
      - app-network
    mem_limit: 512M
    command:
      - --skip-performance-schema
      - --innodb-buffer-pool-size=64M
      - --max-connections=15

  apache:
    image: leafok/lbbs-apache:testing
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile/dockerfile.apache.testing
    ports:
      - "8080:8081"
    volumes:
      - www-data:/var/www/html
      - apache-logs:/usr/local/apache2/logs
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: leafok/lbbs-php:testing
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile/dockerfile.php.testing
    volumes:
      - www-data:/var/www/html
      - php-sessions:/var/lib/php/sessions
      - apache-logs:/usr/local/apache2/logs
    depends_on:
      mysql:
        condition: service_started
        restart: true
    networks:
      - app-network
    expose:
      - "9000"
    command: [ "php-fpm" ]

  bbsd-prepare:
    image: leafok/lbbs-bbsd:testing
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile/dockerfile.bbsd.testing
    volumes:
      - bbsd-conf:/usr/local/lbbs/conf
      - bbsd-data:/usr/local/lbbs/data
      - bbsd-var:/usr/local/lbbs/var
      - bbsd-log:/usr/local/lbbs/log
      - bbsd-utils-conf:/usr/local/lbbs/utils/conf
    depends_on:
      mysql:
        condition: service_started
        restart: true
    networks:
      - app-network
    command: [ "/bin/sh", "/usr/local/lbbs/bin/bbsd_prepare.sh" ]

  bbsd:
    image: leafok/lbbs-bbsd:testing
    restart: unless-stopped
    shm_size: '4gb'
    ports:
      - "2322:2322"
      - "2323:2323"
    volumes:
      - bbsd-conf:/usr/local/lbbs/conf
      - bbsd-data:/usr/local/lbbs/data
      - bbsd-var:/usr/local/lbbs/var
      - bbsd-log:/usr/local/lbbs/log
      - bbsd-utils-conf:/usr/local/lbbs/utils/conf
    depends_on:
      bbsd-prepare:
        condition: service_completed_successfully
    networks:
      - app-network
    command: [ "/usr/local/lbbs/bin/bbsd", "-f" ]

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    # Volume for persistent storage of mysql data
    driver: local
  www-data:
    # Volume for persistent storage of web data
    driver: local
  php-sessions:
    # Volume for persistent storage of PHP session data
    driver: local
  apache-logs:
    # Volume for persistent storage of Apache logs
    driver: local
  bbsd-conf:
    driver: local
  bbsd-data:
    driver: local
  bbsd-var:
    driver: local
  bbsd-log:
    driver: local
  bbsd-utils-conf:
    driver: local
