# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  schedule:
    # Run every day 05:10 UTC+8
    - cron: '10 21 * * *'

env:
  DOCKERHUB_PLATFORMS: linux/amd64,linux/arm64
  APACHE_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/lbbs-apache
  PHP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/lbbs-php
  BBSD_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/lbbs-bbsd

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set current date as env variable
        run: echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # fetch all history if the action needs it

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image (apache)
        id: push-apache
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.DOCKERHUB_PLATFORMS }}
          context: .
          file: Dockerfile/dockerfile.apache.testing
          push: true
          tags: |
            ${{ env.APACHE_IMAGE }}:testing-${{ env.BUILD_DATE }}
            ${{ env.APACHE_IMAGE }}:testing
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build the Docker image (php)
        id: push-php
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.DOCKERHUB_PLATFORMS }}
          context: .
          file: Dockerfile/dockerfile.php.testing
          push: true
          tags: |
            ${{ env.PHP_IMAGE }}:testing-${{ env.BUILD_DATE }}
            ${{ env.PHP_IMAGE }}:testing
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build the Docker image (bbsd)
        id: push-bbsd
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.DOCKERHUB_PLATFORMS }}
          context: .
          file: Dockerfile/dockerfile.bbsd.testing
          push: true
          tags: |
            ${{ env.BBSD_IMAGE }}:testing-${{ env.BUILD_DATE }}
            ${{ env.BBSD_IMAGE }}:testing
          labels: ${{ steps.meta.outputs.labels }}
