name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 # fetch all history if the action needs it

    - name: Build the Docker image (apache)
      uses: docker/build-push-action@v5
      with:
        context: ./leafok_bbs
        file: ./leafok_bbs/Dockerfile/dockerfile.apache
        tags: lbbs-apache:latest

    - name: Build the Docker image (php)
      uses: docker/build-push-action@v5
      with:
        context: ./leafok_bbs
        file: ./leafok_bbs/Dockerfile/dockerfile.php
        tags: lbbs-php:latest

    - name: Build the Docker image (bbsd)
      uses: docker/build-push-action@v5
      with:
        context: ./lbbs
        file: ./leafok_bbs/Dockerfile/dockerfile.bbsd
        tags: lbbs-bbsd:latest

    - name: Build the Docker image (apache:testing)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile/dockerfile.apache.testing
        tags: lbbs-apache:testing

    - name: Build the Docker image (bbsd:testing)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile/dockerfile.bbsd.testing
        tags: lbbs-bbsd:testing
